---
# Tasks to configure firewall rpc-statd.service port and avoid a random port

- name: Configure firewall rpc-statd.service port
  lineinfile:
    path: /etc/sysconfig/nfs
    regexp: '^STATD_PORT='
    insertafter: '^#STATD_PORT='
    line: "STATD_PORT={{ nfs_client_rpc_statd_port }}"
    # line: "STATD_PORT={{ grp_all_rpc_statd_service_fixed_port }}"
  register: rpc_statd_service_config_result

- name: Restart rpc-statd.service to apply configuration
  when: rpc_statd_service_config_result is changed
  systemd:
    state: restarted
    daemon_reload: yes
    name: rpc-statd.service
