---
# Role tasks

- name: setup nfs mount points
  include_role:
    name: amtega.mounts
  vars:
    mounts: "{{ nfs_client_mounts }}"
    mounts_defaults: >-
      {{ nfs_client_mounts_defaults | combine({ 'fstype': 'nfs' }) }}
    mounts_create_paths: "{{ nfs_client_mounts_create_paths }}"
  tags:
    - role::nfs_client
