---
# Role tasks

- name: Main
  vars:
    nfs_client_mounts_to_manage: >-
      {{ nfs_client_mounts
         + ((nfs_client_load_mounts_from_hostvars)
            | ternary(nfs_client_hostvars_mounts
                      | default([])
                      | flatten,
                      [])) }}
  tags:
    - role::nfs_client
  block:
    - when: nfs_client_create_src_dir | bool
      include_tasks: create_src_dir.yml

    - include_tasks: nfs_mounts.yml

    - when: nfs_client_rpc_statd_port is defined
      include_tasks: firewall_rpc_statd.yml
