---
# Tasks to setup nfs mounts

- name: Setup nfs mount points
  ansible.builtin.include_role:
    name: amtega.mounts
  vars:
    mounts: "{{ lookup('template', 'mounts.yml.j2') | from_yaml }}"
    mounts_defaults: "{{ nfs_client_mounts_defaults }}"
    mounts_create_paths: "{{ nfs_client_mounts_create_paths }}"
    mounts_load_from_hostvars: no
  tags:
    - role::nfs_client