---
# Tasks to configure rpc-statd.service port

- name: Configure rpc-statd.service port
  lineinfile:
    path: /etc/sysconfig/nfs
    regexp: '^STATD_PORT='
    insertafter: '^#STATD_PORT='
    line: "STATD_PORT={{ nfs_client_rpc_statd_port }}"
  register: rpc_statd_service_config_result

- name: Restart rpc-statd.service to apply configuration # noqa no-handler
  service:
    name: rpc-statd
    state: restarted
  when: rpc_statd_service_config_result is changed
  vars:
    nfs_client_rpc_statd_service_name: >-
      {{ (ansible_facts.distribution_major_version is version("6", "<="))
         | ternary("nfslock", "rpc-statd") }}
