---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos6
    dockerfile: Dockerfile.centos6.j2
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:stream8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: quay.io/fedora/fedora:34
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
  - name: "fedora35-${INSTANCE_UUID:-1}"
    image: quay.io/fedora/fedora:35
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_35
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          nfs_client_mounts_hostvar:
            - src: acmeserver:/acmepath3
              path: /mnt/path3
          nfs_client_load_mounts_from_hostvars: yes
          nfs_client_mounts:
            - src: acmeserver:/acmepath1
              path: /mnt/path1
            - src: acmeserver:/acmepath2
              path: /mnt/path2
          nfs_client_mounts_defaults:
            state: present
            opts: ro
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
