---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Read /etc/fstab file
      shell: cat /etc/fstab
      changed_when: no
      register: read_fstab_result

    - name: Check that /etc/fstab contains required mounts
      assert:
        that:
          - >-
            read_fstab_result.stdout
            is search("acmeserver:/acmepath1.*/mnt/path1.*nfs")
          - >-
            read_fstab_result.stdout
            is search("acmeserver:/acmepath2.*/mnt/path2.*nfs")
          - >-
            read_fstab_result.stdout
            is search("acmeserver:/acmepath3.*/mnt/path3.*nfs")
